#!/bin/bash
mencoder "mf://N.*.jpg"  -oac copy -mf fps=$1 -o test_N_fps$1.avi -ovc lavc -lavcopts vcodec=msmpeg4v2:vbitrate=800 
mencoder "mf://V.*.jpg"  -oac copy -mf fps=$1 -o test_V_fps$1.avi -ovc lavc -lavcopts vcodec=msmpeg4v2:vbitrate=800 
mencoder "mf://P.*.jpg"  -oac copy -mf fps=$1 -o test_P_fps$1.avi -ovc lavc -lavcopts vcodec=msmpeg4v2:vbitrate=800 
